/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Tue Feb 18 20:53:06 2020. */

#include "command.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t protobuf_event_t_fields[6] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, protobuf_event_t, type, type, 0),
    PB_FIELD(  2, BYTES   , SINGULAR, STATIC  , OTHER, protobuf_event_t, name, type, 0),
    PB_FIELD(  3, BYTES   , SINGULAR, STATIC  , OTHER, protobuf_event_t, data, name, 0),
    PB_FIELD(  4, FIXED_LENGTH_BYTES, SINGULAR, STATIC  , OTHER, protobuf_event_t, faddr, data, 0),
    PB_FIELD(  5, FIXED_LENGTH_BYTES, SINGULAR, STATIC  , OTHER, protobuf_event_t, taddr, faddr, 0),
    PB_LAST_FIELD
};



/* @@protoc_insertion_point(eof) */
