/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Wed Mar  4 20:16:43 2020. */

#include "command.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t rssi_fields[3] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, rssi, rx, rx, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, rssi, tx, rx, 0),
    PB_LAST_FIELD
};

const pb_field_t protobuf_event_t_fields[7] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, protobuf_event_t, type, type, 0),
    PB_FIELD(  2, BYTES   , SINGULAR, STATIC  , OTHER, protobuf_event_t, name, type, 0),
    PB_FIELD(  3, BYTES   , SINGULAR, STATIC  , OTHER, protobuf_event_t, data, name, 0),
    PB_FIELD(  4, FIXED_LENGTH_BYTES, SINGULAR, STATIC  , OTHER, protobuf_event_t, faddr, data, 0),
    PB_FIELD(  5, FIXED_LENGTH_BYTES, SINGULAR, STATIC  , OTHER, protobuf_event_t, taddr, faddr, 0),
    PB_FIELD(  6, MESSAGE , SINGULAR, STATIC  , OTHER, protobuf_event_t, rssi, taddr, &rssi_fields),
    PB_LAST_FIELD
};



/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(protobuf_event_t, rssi) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_rssi_protobuf_event_t)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(protobuf_event_t, rssi) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_rssi_protobuf_event_t)
#endif


/* @@protoc_insertion_point(eof) */
