#ifndef SETUP_H
#define SETUP_H

#define BLE_PROTOBUF_ENABLED true
#define BLE_PROTOBUF_CONFIG_LOG_ENABLED true
#define BLE_PROTOBUF_BLE_OBSERVER_PRIO 2

// Log Config
#define BLE_PROTOBUF_CONFIG_LOG_LEVEL 3
#define BLE_PROTOBUF_CONFIG_INFO_COLOR 0
#define BLE_PROTOBUF_CONFIG_DEBUG_COLOR 3

#endif //SETUP_H